### ISSUE TITLE
extra quote generates error

### ISSUE THREAD

**Issue by mstuyts** [FirstDraftGIS/fdgis-qgis#1]
In _firstdraftgis.py_ there is a quote too much on line 151

 path_to_img = ':/plugins/FirstDraftGIS/img/''

should become:

 path_to_img = ':/plugins/FirstDraftGIS/img/'

**Comment by DanielJDufour** [comment]
Thank you for catching that.  I fixed this with https://github.com/FirstDraftGIS/fdgis-qgis/commit/f53cc7596169721090c41a2f4b6d7253c7541ddf

However, there will be some delay before this change makes it to the official QGIS Plugins repo.  I submitted a new version and am waiting patiently for it to go through the approval process :)
